spring:
  profiles:
    active: local
---
server:
  port: 8081
  servlet:
    context-path: /tran

spring:
  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true

  # H2 메모리 DB를 위한 설정
  h2:
    console:
      enabled: true                            # h2 콘솔 사용
      path: /h2                                    # localhost:port/h2 로 접근 가능
      settings:
        trace: false                        # Print additional trace information
        web-allow-others: true    # 브라우저로 접근가능하게 하기

  datasource:
    url: jdbc:h2:mem:testdb1
    driverClassName: org.h2.Driver
    initialization-mode: always
    sql-script-encoding: utf-8
    username: sa
    password:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
#    schema: classpath:/schema.sql # spring boot startup 시, 특정 경로의 schema.sql 실행

  db1:
    datasource:
      driver-class-name: org.h2.Driver
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:testdb1  # SqlSessionFactoryBean config 설정을 위한 url
      jdbc-url: jdbc:h2:mem:testdb1 # Tcp, Server 모드 주소 설정
      username: sa
      password:
      config-location: classpath:/sql/Db1SqlMapConfig.xml
      mapper-locations: classpath:/sql/mapper/db1/**/*.xml

  # H2 메모리 DB를 위한 설정
  db2:
    datasource:
      driver-class-name: org.h2.Driver
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:testdb2   # SqlSessionFactoryBean config 설정을 위한 url
      jdbc-url: jdbc:h2:mem:testdb2 # Tcp, Server 모드 주소 설정
      username: sa
      password:
      config-location: classpath:/sql/Db2SqlMapConfig.xml
      mapper-locations: classpath:/sql/mapper/db2/**/*.xml

#  # 단일 DB 설정
#server:
#  datasource:
#   driver-class-name: org.h2.Driver
#   jdbc-url: jdbc:h2:mem:testdb2;DB_CLOSE_DELAY=-1;MODE=MySQL # spring-data-jdbc 설정을 위한 url
#   url: jdbc:h2:mem:testdb2;DB_CLOSE_DELAY=-1;MODE=MySQL   # SqlSessionFactoryBean config 설정을 위한 url
#   #    jdbc-url: jdbc:h2:tcp://localhost:9092/~/test # Tcp, Server 모드 주소 설정
#   username: sa
#   password:
#   initialization-mode: always
#   sql-script-encoding: utf-8
#
#mybatis:
#  config-location: classpath:sql/Db2SqlMapConfig.xml
#  mapper-locations: classpath:sql/mapper/**/*.xml


